spring:
  application:
    name: apex
  ai:
    mistralai:
      api-key: ${MISTRAL_API_KEY}


news:
  api:
    key: ${NEWS_API_KEY}
    base:
      url: https://newsapi.org/v2
    country: us
    url:
      content:
        top:
          headlines: /top-headlines